/-
# Localized sources and the actual observation maps

A nonempty open spatial region `W ⊆ 𝕋²` is fixed.  We build

* the **actual physical fields** of a state and of a source, as continuous functions of the
  torus obtained by synthesis of the actual Fourier states;
* the **localized source subspace** of `Curve0 T`: an honest `ℝ`-submodule consisting of the
  sources whose physical field vanishes outside `W` at every time — kept carefully distinct
  from the stronger condition of compact support strictly inside `W × (0,T)`;
* the two **observations** of a solution: its state restricted to `W` and its
  kernel-dependent velocity restricted to `W`, both proved to be the actual physical maps and
  bounded `ℝ`-linear in the state;
* a **common neighbourhood of the zero source** on which the mild identities and the response
  formulas of two kernels simultaneously hold;
* a **bridge** turning a spatial profile in the real Wiener algebra that vanishes outside `W`,
  multiplied by a continuous time profile, into an element of the localized subspace, with the
  time continuity and boundedness proved.

What is **not** proved *in this file*: the existence of a *nonzero* spatial profile in the
Wiener algebra vanishing outside an arbitrary nonempty open `W`.  It is isolated here as the
explicit hypothesis `HasLocalizedProfile`, and every statement in this file is proved without
it.  In v5.0 that input is **proved** in `SmoothSource`
(`exists_smooth_localized_profile`), in the stronger form of a nonzero `C^∞` profile supported
in a compact subset of `W`.

Part of `LiWangFormalizationObservationBridgePacket` v4.0, with v5.0 corrections to the commentary.
-/
import LiWangFormalization.FractionalRegularity
import LiWangFormalization.SourceVariations

set_option autoImplicit false
set_option relaxedAutoImplicit false

open scoped BigOperators ComplexConjugate
open Filter Topology MeasureTheory

namespace LiWang.Formalization

variable {T : ℝ}

/-! ## Physical fields -/

/-- The **actual physical field** of a first-order state curve at a given time: the synthesis
of its Fourier coefficients, a continuous function of the torus. -/
noncomputable def statePhys (hT : 0 ≤ T) (u : Curve1 T) (t : ℝ) : C(Torus2, ℂ) :=
  synth (incl (curveState hT u t))

/-- The **actual physical field** of a source curve at a given time. -/
noncomputable def sourcePhys (hT : 0 ≤ T) (V : Curve0 T) (t : ℝ) : C(Torus2, ℂ) :=
  synth (sourceFun hT V t)

/-- The **actual physical velocity field** generated by the kernel symbol `m`. -/
noncomputable def velocityPhys (m : Fin 2 → Gam → ℂ) (hm : IsBddSymbol m) (j : Fin 2)
    (hT : 0 ≤ T) (u : Curve1 T) (t : ℝ) : C(Torus2, ℂ) :=
  synth (velocity m hm j (incl (curveState hT u t)))

theorem sourcePhys_add (hT : 0 ≤ T) (V V' : Curve0 T) (t : ℝ) :
    sourcePhys hT (V + V') t = sourcePhys hT V t + sourcePhys hT V' t := by
  rw [sourcePhys, sourcePhys, sourcePhys, ← map_add]
  rfl

theorem sourcePhys_smul (hT : 0 ≤ T) (r : ℝ) (V : Curve0 T) (t : ℝ) :
    sourcePhys hT (r • V) t = (r : ℂ) • sourcePhys hT V t := by
  rw [sourcePhys, sourcePhys, ← map_smul]
  show synth (sourceFun hT (r • V) t) = _
  have hval : sourceFun hT (r • V) t = (r : ℂ) • sourceFun hT V t := by
    show ((r • V) (clampT hT t)).val = _
    rw [BoundedContinuousFunction.smul_apply, RealWiener.val_smul, smul_real_wiener]
    rfl
  rw [hval]

@[simp] theorem sourcePhys_zero (hT : 0 ≤ T) (t : ℝ) :
    sourcePhys hT (0 : Curve0 T) t = 0 := by
  rw [sourcePhys]
  show synth ((0 : Curve0 T) (clampT hT t)).val = 0
  rw [show ((0 : Curve0 T) (clampT hT t)).val = (0 : Wiener) from rfl, map_zero]

/-! ## Vanishing outside the observation region -/

/-- A continuous function of the torus vanishes outside `W`. -/
def VanishesOutside (W : Set Torus2) (F : C(Torus2, ℂ)) : Prop := ∀ x ∉ W, F x = 0

/-- A source curve whose **physical field vanishes outside `W`** at every time.  This is the
weaker of the two localization conditions. -/
def SourceSupportedIn (hT : 0 ≤ T) (W : Set Torus2) (V : Curve0 T) : Prop :=
  ∀ t : ℝ, VanishesOutside W (sourcePhys hT V t)

/-- The **localized source subspace**: an actual `ℝ`-submodule of `Curve0 T`. -/
noncomputable def localizedSources (hT : 0 ≤ T) (W : Set Torus2) : Submodule ℝ (Curve0 T) where
  carrier := {V | SourceSupportedIn hT W V}
  add_mem' := by
    intro V V' hV hV' t x hx
    rw [sourcePhys_add]
    show sourcePhys hT V t x + sourcePhys hT V' t x = 0
    rw [hV t x hx, hV' t x hx, add_zero]
  zero_mem' := by
    intro t x _
    rw [sourcePhys_zero]
    rfl
  smul_mem' := by
    intro r V hV t x hx
    rw [sourcePhys_smul]
    show (r : ℂ) • sourcePhys hT V t x = 0
    rw [hV t x hx, smul_zero]

@[simp] theorem mem_localizedSources (hT : 0 ≤ T) (W : Set Torus2) (V : Curve0 T) :
    V ∈ localizedSources hT W ↔ SourceSupportedIn hT W V := Iff.rfl

/-- The **stronger** localization condition: compact spatial support strictly inside `W`, and
time support in a compact subinterval of `(0,T)`.  Deliberately kept distinct from
`SourceSupportedIn`. -/
def CompactlySupportedIn (hT : 0 ≤ T) (W : Set Torus2) (V : Curve0 T) : Prop :=
  (∃ K : Set Torus2, IsCompact K ∧ K ⊆ W ∧
      ∀ (t : ℝ), ∀ x ∉ K, sourcePhys hT V t x = 0)
    ∧ (∃ t₀ t₁ : ℝ, 0 < t₀ ∧ t₀ ≤ t₁ ∧ t₁ < T ∧
      ∀ t : ℝ, t ∉ Set.Icc t₀ t₁ → sourceFun hT V t = 0)

/-- Compact support strictly inside `W × (0,T)` is strictly stronger: it implies vanishing
outside `W`. -/
theorem CompactlySupportedIn.supportedIn {hT : 0 ≤ T} {W : Set Torus2} {V : Curve0 T}
    (h : CompactlySupportedIn hT W V) : SourceSupportedIn hT W V := by
  obtain ⟨⟨K, _, hKW, hvan⟩, -⟩ := h
  intro t x hx
  exact hvan t x (fun hc => hx (hKW hc))

/-! ## The observation maps are actual, bounded, linear maps -/

/-- The underlying first-order state, as a bounded `ℝ`-linear map. -/
noncomputable def RealWiener1.valCLM : RealWiener1 →L[ℝ] Wiener1 :=
  LinearMap.mkContinuous
    { toFun := RealWiener1.val
      map_add' := fun _ _ => rfl
      map_smul' := fun _ _ => rfl }
    1 (fun u => by rw [one_mul]; exact le_of_eq (RealWiener1.norm_def u))

@[simp] theorem RealWiener1.valCLM_apply (u : RealWiener1) : RealWiener1.valCLM u = u.val := rfl

/-- **The state observation map** at a fixed time: an actual bounded `ℝ`-linear map from the
state curve space to continuous functions of the torus, of norm at most one. -/
noncomputable def statePhysCLM (hT : 0 ≤ T) (t : TimeI T) : Curve1 T →L[ℝ] C(Torus2, ℂ) :=
  LinearMap.mkContinuous
    { toFun := fun u => synth (incl (u t).val)
      map_add' := fun u v => by
        show synth (incl ((u + v) t).val) = synth (incl (u t).val) + synth (incl (v t).val)
        rw [BoundedContinuousFunction.add_apply, RealWiener1.val_add, map_add, map_add]
      map_smul' := fun r u => by
        show synth (incl ((r • u) t).val) = _
        rw [BoundedContinuousFunction.smul_apply, RealWiener1.val_smul, smul_real_wiener1,
          map_smul, map_smul]
        show ((r : ℂ)) • synth (incl (u t).val) = (RingHom.id ℝ) r • synth (incl (u t).val)
        ext x
        show ((r : ℂ)) * (synth (incl (u t).val)) x = r • (synth (incl (u t).val)) x
        rw [Complex.real_smul] }
    1 (fun u => by
      rw [one_mul]
      calc ‖synth (incl (u t).val)‖ ≤ ‖incl (u t).val‖ := norm_synth_apply_le _
        _ ≤ ‖(u t).val‖ := norm_incl_apply_le _
        _ = ‖u t‖ := (RealWiener1.norm_def (u t)).symm
        _ ≤ ‖u‖ := u.norm_coe_le_norm t)

/-- The bounded linear observation map really is the physical field. -/
theorem statePhysCLM_apply (hT : 0 ≤ T) (t : TimeI T) (u : Curve1 T) :
    statePhysCLM hT t u = statePhys hT u (t : ℝ) := by
  rw [statePhys, curveState_coe hT u t]
  rfl

theorem norm_statePhys_le (hT : 0 ≤ T) (u : Curve1 T) (t : TimeI T) :
    ‖statePhys hT u (t : ℝ)‖ ≤ ‖u‖ := by
  rw [statePhys, curveState_coe hT u t]
  calc ‖synth (incl (u t).val)‖ ≤ ‖incl (u t).val‖ := norm_synth_apply_le _
    _ ≤ ‖(u t).val‖ := norm_incl_apply_le _
    _ = ‖u t‖ := (RealWiener1.norm_def (u t)).symm
    _ ≤ ‖u‖ := u.norm_coe_le_norm t

/-- **The velocity observation map** at a fixed time: again an actual bounded `ℝ`-linear map,
built from the actual velocity multiplier of the kernel symbol. -/
noncomputable def velocityPhysCLM (m : Fin 2 → Gam → ℂ) (hm : IsBddSymbol m) (j : Fin 2)
    (hT : 0 ≤ T) (t : TimeI T) : Curve1 T →L[ℝ] C(Torus2, ℂ) :=
  LinearMap.mkContinuousOfExistsBound
    { toFun := fun u => synth (velocity m hm j (incl (u t).val))
      map_add' := fun u v => by
        show synth (velocity m hm j (incl ((u + v) t).val)) = _
        rw [BoundedContinuousFunction.add_apply, RealWiener1.val_add, map_add, map_add, map_add]
      map_smul' := fun r u => by
        show synth (velocity m hm j (incl ((r • u) t).val)) = _
        rw [BoundedContinuousFunction.smul_apply, RealWiener1.val_smul, smul_real_wiener1,
          map_smul, map_smul, map_smul]
        show ((r : ℂ)) • synth (velocity m hm j (incl (u t).val))
          = (RingHom.id ℝ) r • synth (velocity m hm j (incl (u t).val))
        ext x
        show ((r : ℂ)) * (synth (velocity m hm j (incl (u t).val))) x
          = r • (synth (velocity m hm j (incl (u t).val))) x
        rw [Complex.real_smul] }
    ⟨Classical.choose hm, fun u => by
      have hC := Classical.choose_spec hm
      calc ‖synth (velocity m hm j (incl (u t).val))‖
          ≤ ‖velocity m hm j (incl (u t).val)‖ := norm_synth_apply_le _
        _ ≤ Classical.choose hm * ‖incl (u t).val‖ := norm_velocity_apply_le hm j hC _
        _ ≤ Classical.choose hm * ‖u‖ := by
            have hC0 : (0:ℝ) ≤ Classical.choose hm := nonneg_of_symbol_bound hC
            have h1 : ‖incl (u t).val‖ ≤ ‖u‖ :=
              le_trans (norm_incl_apply_le _)
                (le_trans (le_of_eq (RealWiener1.norm_def (u t)).symm) (u.norm_coe_le_norm t))
            exact mul_le_mul_of_nonneg_left h1 hC0⟩

theorem velocityPhysCLM_apply (m : Fin 2 → Gam → ℂ) (hm : IsBddSymbol m) (j : Fin 2)
    (hT : 0 ≤ T) (t : TimeI T) (u : Curve1 T) :
    velocityPhysCLM m hm j hT t u = velocityPhys m hm j hT u (t : ℝ) := by
  rw [velocityPhys, curveState_coe hT u t]
  rfl

theorem norm_velocityPhys_le {m : Fin 2 → Gam → ℂ} (hm : IsBddSymbol m) {C : ℝ}
    (hC : ∀ j k, ‖m j k‖ ≤ C) (j : Fin 2) (hT : 0 ≤ T) (u : Curve1 T) (t : TimeI T) :
    ‖velocityPhys m hm j hT u (t : ℝ)‖ ≤ C * ‖u‖ := by
  have hC0 : 0 ≤ C := nonneg_of_symbol_bound hC
  rw [velocityPhys, curveState_coe hT u t]
  calc ‖synth (velocity m hm j (incl (u t).val))‖
      ≤ ‖velocity m hm j (incl (u t).val)‖ := norm_synth_apply_le _
    _ ≤ C * ‖incl (u t).val‖ := norm_velocity_apply_le hm j hC _
    _ ≤ C * ‖u‖ := by
        have h1 : ‖incl (u t).val‖ ≤ ‖u‖ :=
          le_trans (norm_incl_apply_le _)
            (le_trans (le_of_eq (RealWiener1.norm_def (u t)).symm) (u.norm_coe_le_norm t))
        exact mul_le_mul_of_nonneg_left h1 hC0

/-- **The two observations**: the physical state and the physical velocity, restricted to the
observation region `W`. -/
noncomputable def obsState (hT : 0 ≤ T) (W : Set Torus2) (u : Curve1 T) : ℝ → W → ℂ :=
  fun t x => statePhys hT u t (x : Torus2)

noncomputable def obsVelocity (m : Fin 2 → Gam → ℂ) (hm : IsBddSymbol m) (j : Fin 2)
    (hT : 0 ≤ T) (W : Set Torus2) (u : Curve1 T) : ℝ → W → ℂ :=
  fun t x => velocityPhys m hm j hT u t (x : Torus2)

theorem obsState_eq (hT : 0 ≤ T) (W : Set Torus2) (u : Curve1 T) (t : ℝ) (x : W) :
    obsState hT W u t x = synth (incl (curveState hT u t)) (x : Torus2) := rfl

theorem obsVelocity_eq (m : Fin 2 → Gam → ℂ) (hm : IsBddSymbol m) (j : Fin 2) (hT : 0 ≤ T)
    (W : Set Torus2) (u : Curve1 T) (t : ℝ) (x : W) :
    obsVelocity m hm j hT W u t x
      = synth (velocity m hm j (incl (curveState hT u t))) (x : Torus2) := rfl

/-! ## A common neighbourhood of the zero source for two kernels -/

/-- **A common neighbourhood of the zero source** on which the proved mild identity and the
response formulas hold for *both* kernels simultaneously. -/
theorem eventually_two_kernel_mild {α : ℝ} (hα : 1 / 2 < α) (hT : 0 ≤ T)
    {m₁ m₂ : Fin 2 → Gam → ℂ} (hm₁ : IsBddSymbol m₁) (hr₁ : IsRealSymbol m₁)
    (hm₂ : IsBddSymbol m₂) (hr₂ : IsRealSymbol m₂) :
    ∀ᶠ f in 𝓝 (0 : Curve0 T),
      (sourceSolution hα hT hm₁ hr₁ f
          + sourceQuad hα hT m₁ hm₁ hr₁ (sourceSolution hα hT hm₁ hr₁ f)
              (sourceSolution hα hT hm₁ hr₁ f) = duhamelOp hα hT f)
        ∧ (sourceSolution hα hT hm₂ hr₂ f
          + sourceQuad hα hT m₂ hm₂ hr₂ (sourceSolution hα hT hm₂ hr₂ f)
              (sourceSolution hα hT hm₂ hr₂ f) = duhamelOp hα hT f) :=
  (eventually_sourceSolution_eq hα hT hm₁ hr₁).and (eventually_sourceSolution_eq hα hT hm₂ hr₂)

/-- The same, as an explicit radius, and restricted to the localized source subspace — no
derivative identity is assumed here, only the two mild identities. -/
theorem exists_radius_two_kernel_mild {α : ℝ} (hα : 1 / 2 < α) (hT : 0 ≤ T)
    {m₁ m₂ : Fin 2 → Gam → ℂ} (hm₁ : IsBddSymbol m₁) (hr₁ : IsRealSymbol m₁)
    (hm₂ : IsBddSymbol m₂) (hr₂ : IsRealSymbol m₂) (W : Set Torus2) :
    ∃ ε > 0, ∀ f ∈ localizedSources hT W, ‖f‖ < ε →
      (sourceSolution hα hT hm₁ hr₁ f
          + sourceQuad hα hT m₁ hm₁ hr₁ (sourceSolution hα hT hm₁ hr₁ f)
              (sourceSolution hα hT hm₁ hr₁ f) = duhamelOp hα hT f)
        ∧ (sourceSolution hα hT hm₂ hr₂ f
          + sourceQuad hα hT m₂ hm₂ hr₂ (sourceSolution hα hT hm₂ hr₂ f)
              (sourceSolution hα hT hm₂ hr₂ f) = duhamelOp hα hT f) := by
  obtain ⟨ε, hε, hball⟩ := Metric.eventually_nhds_iff.1
    (eventually_two_kernel_mild hα hT hm₁ hr₁ hm₂ hr₂)
  refine ⟨ε, hε, fun f _ hf => hball ?_⟩
  rwa [dist_zero_right]

/-! ## The bridge: a spatial profile times a time profile -/

/-- The product source `V(t) = χ(t) · a`: a continuous real time profile times a real spatial
profile in the Wiener algebra.  This is an actual element of `Curve0 T`. -/
noncomputable def productSource (hT : 0 ≤ T) (a : RealWiener) {χ : ℝ → ℝ}
    (hχ : Continuous χ) : Curve0 T :=
  BoundedContinuousFunction.mkOfCompact
    ⟨fun t : TimeI T => χ (t : ℝ) • a,
      (hχ.comp continuous_subtype_val).smul continuous_const⟩

@[simp] theorem productSource_apply (hT : 0 ≤ T) (a : RealWiener) {χ : ℝ → ℝ}
    (hχ : Continuous χ) (t : TimeI T) : productSource hT a hχ t = χ (t : ℝ) • a := rfl

theorem sourceFun_productSource (hT : 0 ≤ T) (a : RealWiener) {χ : ℝ → ℝ}
    (hχ : Continuous χ) (s : ℝ) :
    sourceFun hT (productSource hT a hχ) s = χ ((clampT hT s : TimeI T) : ℝ) • a.val := rfl

theorem sourcePhys_productSource (hT : 0 ≤ T) (a : RealWiener) {χ : ℝ → ℝ}
    (hχ : Continuous χ) (s : ℝ) (x : Torus2) :
    sourcePhys hT (productSource hT a hχ) s x
      = ((χ ((clampT hT s : TimeI T) : ℝ) : ℝ) : ℂ) * synth a.val x := by
  rw [sourcePhys, sourceFun_productSource, smul_real_wiener, map_smul]
  rfl

/-- **The bridge**: if the spatial profile vanishes outside `W`, the product source lies in the
localized source subspace. -/
theorem productSource_mem_localizedSources (hT : 0 ≤ T) {W : Set Torus2} (a : RealWiener)
    {χ : ℝ → ℝ} (hχ : Continuous χ) (ha : ∀ x ∉ W, synth a.val x = 0) :
    productSource hT a hχ ∈ localizedSources hT W := by
  intro s x hx
  rw [sourcePhys_productSource, ha x hx, mul_zero]

/-- The bridge preserves nontriviality. -/
theorem productSource_ne_zero (hT : 0 ≤ T) (a : RealWiener) {χ : ℝ → ℝ} (hχ : Continuous χ)
    (ha : a ≠ 0) {t₀ : TimeI T} (hχ0 : χ (t₀ : ℝ) ≠ 0) : productSource hT a hχ ≠ 0 := by
  intro hz
  have h := congrArg (fun V : Curve0 T => V t₀) hz
  have h0 : χ (t₀ : ℝ) • a = 0 := h
  exact ha (by
    have := smul_eq_zero.1 h0
    rcases this with h1 | h1
    · exact absurd h1 hχ0
    · exact h1)

/-- **The bridge, in the stronger compactly-supported form.** -/
theorem productSource_compactlySupported (hT : 0 ≤ T) {W : Set Torus2} (a : RealWiener)
    {χ : ℝ → ℝ} (hχ : Continuous χ) {K : Set Torus2} (hK : IsCompact K) (hKW : K ⊆ W)
    (ha : ∀ x ∉ K, synth a.val x = 0) {t₀ t₁ : ℝ} (ht₀ : 0 < t₀) (ht : t₀ ≤ t₁) (ht₁ : t₁ < T)
    (hsupp : ∀ t : ℝ, t ∉ Set.Icc t₀ t₁ → χ t = 0) :
    CompactlySupportedIn hT W (productSource hT a hχ) := by
  refine ⟨⟨K, hK, hKW, ?_⟩, ⟨t₀, t₁, ht₀, ht, ht₁, ?_⟩⟩
  · intro s x hx
    rw [sourcePhys_productSource, ha x hx, mul_zero]
  · intro s hs
    rw [sourceFun_productSource]
    have hval : χ ((clampT hT s : TimeI T) : ℝ) = 0 := by
      refine hsupp _ ?_
      intro hmem
      rcases le_or_gt 0 s with h0 | h0
      · rcases le_or_gt s T with hT' | hT'
        · rw [clampT_coe hT h0 hT'] at hmem
          exact hs hmem
        · have hc : ((clampT hT s : TimeI T) : ℝ) = T := by
            show min (max s 0) T = T
            rw [max_eq_left h0, min_eq_right hT'.le]
          rw [hc] at hmem
          exact absurd hmem.2 (not_le.2 ht₁)
      · have hc : ((clampT hT s : TimeI T) : ℝ) = 0 := by
          show min (max s 0) T = 0
          rw [max_eq_right h0.le, min_eq_left hT]
        rw [hc] at hmem
        exact absurd hmem.1 (not_le.2 ht₀)
    rw [hval, zero_smul]

/-! ## The single missing existence input, isolated -/

/-- For a nonempty open region `W`, the existence of a *nonzero* real state of the Wiener
algebra whose physical field vanishes outside `W`.

In v4.0 this was an unproved input.  In v5.0 it is **proved** for every nonempty open `W`:
see `LiWang.Formalization.exists_smooth_localized_profile` in `SmoothSource`, which produces a
nonzero real profile that is moreover `C^∞` and supported in a compact subset of `W`.  The
predicate is kept because several statements below are still phrased with it as an explicit
hypothesis. -/
def HasLocalizedProfile (W : Set Torus2) : Prop :=
  ∃ a : RealWiener, a ≠ 0 ∧ ∀ x ∉ W, synth a.val x = 0

/-- An explicit **continuous** time profile supported in `[T/4, 3T/4] ⊂ (0,T)` and nonzero at
`T/2`.  It is continuous but **not** `C¹` at the support endpoints when `T > 0`, so it cannot
serve as a smooth compactly supported time test; it is retained only as a continuous-only
example.  The genuinely `C^∞` compactly supported time bump is
`LiWang.Formalization.smoothTimeBump` in `SmoothSource`. -/
noncomputable def timeProfile (T : ℝ) : ℝ → ℝ :=
  fun t => max 0 ((t - T / 4) * (3 * T / 4 - t))

theorem continuous_timeProfile (T : ℝ) : Continuous (timeProfile T) :=
  continuous_const.max ((continuous_id.sub continuous_const).mul
    (continuous_const.sub continuous_id))

theorem timeProfile_eq_zero {T : ℝ} (hT : 0 ≤ T) {t : ℝ}
    (ht : t ∉ Set.Icc (T / 4) (3 * T / 4)) : timeProfile T t = 0 := by
  rw [timeProfile, max_eq_left]
  rcases not_and_or.1 (fun h : T / 4 ≤ t ∧ t ≤ 3 * T / 4 => ht ⟨h.1, h.2⟩) with h | h
  · have hlt := not_le.1 h
    have h1 : t - T / 4 < 0 := by linarith
    have h2 : 0 < 3 * T / 4 - t := by linarith
    nlinarith
  · have hlt := not_le.1 h
    have h1 : 0 < t - T / 4 := by linarith
    have h2 : 3 * T / 4 - t < 0 := by linarith
    nlinarith

theorem timeProfile_mid_pos {T : ℝ} (hT : 0 < T) : 0 < timeProfile T (T / 2) := by
  rw [timeProfile]
  have h : 0 < (T / 2 - T / 4) * (3 * T / 4 - T / 2) := by nlinarith
  exact lt_max_of_lt_right h

/-- **Non-vacuity, conditional on the missing input**: the localized source subspace contains a
nonzero element which is even compactly supported inside `W × (0,T)`. -/
theorem exists_nonzero_compactlySupported_source {T : ℝ} (hT : 0 < T) {W : Set Torus2}
    {K : Set Torus2} (hK : IsCompact K) (hKW : K ⊆ W) {a : RealWiener} (ha : a ≠ 0)
    (haK : ∀ x ∉ K, synth a.val x = 0) :
    ∃ V ∈ localizedSources hT.le W, V ≠ 0 ∧ CompactlySupportedIn hT.le W V := by
  have hχ := continuous_timeProfile T
  refine ⟨productSource hT.le a hχ, ?_, ?_, ?_⟩
  · exact productSource_mem_localizedSources hT.le a hχ
      (fun x hx => haK x (fun hc => hx (hKW hc)))
  · have hmem : T / 2 ∈ Set.Icc (0:ℝ) T := ⟨by linarith, by linarith⟩
    refine productSource_ne_zero hT.le a hχ ha (t₀ := ⟨T / 2, hmem⟩) ?_
    exact ne_of_gt (timeProfile_mid_pos hT)
  · exact productSource_compactlySupported hT.le a hχ hK hKW haK
      (t₀ := T / 4) (t₁ := 3 * T / 4) (by linarith) (by linarith) (by linarith)
      (fun t ht => timeProfile_eq_zero hT.le ht)

theorem exists_nonzero_localizedSource {T : ℝ} (hT : 0 < T) {W : Set Torus2}
    (h : HasLocalizedProfile W) : ∃ V ∈ localizedSources hT.le W, V ≠ 0 := by
  obtain ⟨a, ha, haW⟩ := h
  have hχ := continuous_timeProfile T
  refine ⟨productSource hT.le a hχ, productSource_mem_localizedSources hT.le a hχ haW, ?_⟩
  have hmem : T / 2 ∈ Set.Icc (0:ℝ) T := ⟨by linarith, by linarith⟩
  exact productSource_ne_zero hT.le a hχ ha (t₀ := ⟨T / 2, hmem⟩)
    (ne_of_gt (timeProfile_mid_pos hT))

end LiWang.Formalization
